
##--\u5173\u95EDbasic\u8BA4\u8BC1
security:
    basic:
        enabled: false
server:
    port: 3000
spring:
    application:
        name: api_gateway
##--MySQL\u914D\u7F6E
    datasource:
        driver-class-name: com.mysql.jdbc.Driver #(com.mysql.jdbc.jdbc2.optional.MysqlDataSource)
        url: jdbc:mysql://127.0.0.1:3306/zth_test?characterEncoding=UTF-8
        username: root
        password: root
##--MySQL Druid\u8FDE\u63A5\u6C60  DruidDataSource\u914D\u7F6E\u5C5E\u6027\u5217\u8868 \u53C2\u8003\uFF1Ahttps://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8
        initialSize: 50
        maxActive: 100
        minIdle: 5
        maxWait: 60000
        validationQuery: select 1
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 50
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 25200000
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
        filters: stat
#zipkin\u7684\u670D\u52A1\u5668\u5730\u5740(\u53D1\u9001 Trace \u5230\u8BE5\u5730\u5740)
    zipkin:
        base-url: http://zipkin-server:9411/

##


##-- \u81EA\u5B9A\u4E49\u5C5E\u6027 key=value
##--\u5065\u5EB7\u663E\u793A\u4FE1\u606F spring boot actuator \u7684demo\u6D4B\u8BD5\u914D\u7F6E
info:
    build:
        artifact: '@project.artifactId@'
        description: '@project.description@'
        name: '@project.name@'
        version: '@project.version@'
##-- OAuth2\u8BA4\u8BC1\u670D\u52A1\u8BF7\u6C42\u5730\u5740(\u7533\u8BF7\u83B7\u53D6AccessToken\u7684\u8D44\u6E90\u548C\u8BA4\u8BC1\u670D\u52A1\u5668)
oauth2:
    serverPath: http://127.0.0.1:8084/oauth2/oauth/token
eureka:
  client:
    eureka-server-connect-timeout-seconds: 10

##\u5BF9\u4E8E\u6BCF\u4E00\u4E2A\u8DEF\u7531 \u8BBE\u7F6E\u6700\u5927\u7684\u8FDE\u63A5\u6570\u91CF
zuul:
  host:
    max-per-route-connections: 20


