eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1000/eureka/
security:
    basic:
        enabled: false
server:
    context-path: /oauth2
    port: 8084
spring:
    application:
        name: eureka-oauth2-server
##--MySQL\u914D\u7F6E
    datasource:
        driver-class-name: com.mysql.jdbc.Driver #(com.mysql.jdbc.jdbc2.optional.MysqlDataSource)
        url: jdbc:mysql://127.0.0.1:3306/zth_test?characterEncoding=UTF-8
        username: root
        password: root
##--MySQL Druid\u8FDE\u63A5\u6C60  DruidDataSource\u914D\u7F6E\u5C5E\u6027\u5217\u8868 \u53C2\u8003\uFF1Ahttps://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8
        initialSize: 50
        maxActive: 100
        minIdle: 5
        maxWait: 60000
        validationQuery: select 1
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 50
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 25200000
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
        filters: stat
